########################################################################################################################
# 功能: 启动容器
# 容器:
#   - discovery:                  服务注册与发现节点
#   - compute-service:            数值计算服务
# 作者: 应卓
# 日期: 2016-09-17
########################################################################################################################

discovery:
  mem_limit: 1000000000
  image: yingzhuo/microservice-discovery:latest
  ports:
    - 8761:9761
  volumes:
    - /tmp:/tmp
  environment:
    - SPRING_PROFILES_ACTIVE=docker
    - JAVA_OPTS="-Xms5000m -Xmx10000m"
  command: bash -c "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"

compute-service:
  mem_limit: 1000000000
  image: yingzhuo/microservice-compute-service:latest
  ports:
    - 7777:7777
  volumes:
    - /tmp:/tmp
  environment:
    - SPRING_PROFILES_ACTIVE=docker
    - JAVA_OPTS="-Xms5000m -Xmx10000m"
  links:
      - discovery:discovery
  command: bash -c "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"